version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: transitflow
      POSTGRES_USER: transitflow
      POSTGRES_PASSWORD: transitflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transitflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://transitflow:transitflow@postgres:5432/transitflow
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./files:/app/files:ro
      - .:/app

volumes:
  postgres_data:
  redis_data:
